name: Deploy Uboor to GitHub Pages

on:
  push:
    branches:
      - main # الروبوت سيعمل فقط عند رفع كود جديد على هذا الفرع

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # إعطاء صلاحية للروبوت للكتابة ورفع الملفات

    steps:
      - name: Checkout Code 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: "20" # نستخدم أحدث نسخة مستقرة من بيئة نود

      - name: Install Dependencies 📦
        run: npm install

      - name: Build Project 🏗️
        run: |
          npm run build
          cp dist/index.html dist/404.html

          # 🌟 خدعة الـ SEO: إنشاء مجلدات حقيقية لكل مسار في الموقع
          mkdir -p dist/about dist/services dist/contact dist/privacy

          # نسخ ملف React الأساسي داخل هذه المجلدات لكي يعيد غيت هاب الرمز 200 OK لجوجل
          cp dist/index.html dist/about/index.html
          cp dist/index.html dist/services/index.html
          cp dist/index.html dist/contact/index.html
          cp dist/index.html dist/privacy/index.html

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # المجلد الذي يتم توليده بعد البناء في Vite
          cname: uboor.org
